server {
  listen 443 ssl;
  server_name localhost;

  ssl_certificate /etc/nginx/certs/site.fullchain.crt;
  ssl_certificate_key /etc/nginx/certs/site.key;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}
